imports:
     - { resource: "@ToroSeoBundle/Resources/config/app/sylius_resource.yml" }
     - { resource: "@ToroSeoBundle/Resources/config/app/sitemap.yml" }

framework:
    cache:
        pools:
            seo_meta_data.cache:
                adapter: cache.app
                public: false
                default_lifetime: 86400
